version: '3.8'

services:
  worker_fetcher:
    build: .
    container_name: celery_fetcher
    command: celery -A app.celery worker -Q fetcher --loglevel=info
    environment:
      - REDIS_URL=${REDIS_URL}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}